spring:
  output:
    ansi:
      enabled:
        ALWAYS

  application:
    name: final

  config:
    import: optional:file:.env[.properties]
    #스프링 도커 컨테이너에서 실행되면 필요 없음. 단, 로컬 개발시 필요한 사람이 있을 수 있을 것 같아 남겨둡니다.

  #시간 설정
  jackson:
    time-zone: Asia/Seoul

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
    #      schema-locations:
    #        - classpath:db/schema.sql

  # JWT
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

  # SwaggerUI 설정
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE