spring:
  output:
    ansi:
      enabled:
        ALWAYS

  application:
    name: final

  config:
    import: optional:file:.env[.properties]

  #시간 설정
  jackson:
    time-zone: Asia/Seoul

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
    #      schema-locations:
    #        - classpath:db/schema.sql

  # Redis
  data:
    redis:
      repositories:
        enabled: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  # SwaggerUI 설정
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui

  # 메일 의존성
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT
jwt:
  secret: ${JWT_SECRET}
  refresh_secret : ${JWT_REFRESH_SECRET}

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 백엔드 도메인
cors:
  backend-origin: ${BACKEND_DOMAIN}

# 스웨거 https 인식
server:
  forward-headers-strategy: framework

# 이메일 인증
email:
  verification-url: ${EMAIL_VERIFICATION_URL}
frontend:
  url: ${FRONTEND_URL}