spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
#      schema-locations:
#        - classpath:db/schema.sql