spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_DATABASE}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/schema.sql