spring:
  application:
    name: final

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: "jdbc:mysql://localhost:3306/${LOCALDB_DATABASE}"
    username: ${LOCALDB_USER}
    password: ${LOCALDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


