spring:

  application:
    name: final

  config:
    import: optional:file:.env[.properties]

  #시간 설정
  jackson:
    time-zone: Asia/Seoul

  # JPA
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: "jdbc:mysql://localhost:3306/${LOCALDB_DATABASE}"
    username: ${LOCALDB_USER}
    password: ${LOCALDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver